---
- name: install charles
  hosts: charles
  gather_facts: false
  serial: 1
  vars: 
    apps:
      - microsoft-windows-terminal
      - libreoffice-fresh
      - vcvrack
      - vlc
      - powertoys
      - 7zip
      - cura-new
      - firefox

  tasks:
    - name: install apps
      win_chocolatey:
        name: '{{ item }}'
        state: present
      loop: 
        "{{ apps }}"
      tags: 
      - install

    - name: Create directory retrogame
      ansible.windows.win_file:
        path: '%public%\desktop\retro'
        state: directory
      tags:
        - retro
        - arena
        - war3
        - tmnf
        - revolt
        - zeus
        

    # TODO c'est moche le openarene/openarena-0.8.8 ?
    - name: "install retrogame : open arena"
      win_unzip:
        src: '\\serveur\partage\retrogame\openarena-0.8.8.zip'
        dest: '%programfiles%\openarena'
      tags:
        - retro
        - arena

    - name: "create shortcut: arena"
      win_shortcut:  
        src: '%programfiles%\openarena\openarena-0.8.8\openarena.exe'
        dest: '%public%\desktop\retro\arena.lnk'
        icon: '%programfiles%\openarena\openarena-0.8.8\openarena.exe,0'
        directory: '%programfiles%\openarena\openarena-0.8.8'
        state: present
      tags:
        - retro
        - arena
        - shortcut

    - name: "install retrogame : war3"
      win_unzip:
        src: '\\serveur\partage\retrogame\w3\Warcraft III.zip'
        dest: '%programfiles%\'
      tags:
        - retro
        - war3

      # win_copy:
      #   src: '\\serveur\partage\retrogame\warcraft3'
      #   dest: "%programfiles%"
      # tags:
      #   - retro
      #   - war3

    - name: "create shortcut: war3"
      win_shortcut:
        src: '%programfiles%\Warcraft III\warcraft III.exe'
        dest: '%public%\desktop\retro\war3.lnk'
        icon: '%programfiles%\Warcraft III\warcraft III.exe,0'
        state: present
      tags:
        - retro
        - war3
        - shortcut

    - name: "create shortcut: war3 frozen throne"
      win_shortcut:
        src: '%programfiles%\Warcraft III\frozen throne.exe'
        dest: '%public%\desktop\retro\frozen throne.lnk'
        icon: '%programfiles%\Warcraft III\frozen throne.exe,0'
        state: present
      tags:
        - retro
        - war3        
        - shortcut

    - name: copy map war3
      win_copy:
        src: '\\serveur\partage\retrogame\map_war3'
        dest: '%programfiles%\Warcraft III\maps\dl'
        remote_src: true
      tags:
        - retro
        - war3
    ## copy files
    ##copy war3 dans c:/programfiles/war3 ?
    ##copy les map dl dans war3

    ## trackmania ?
    # - name: Install .Net 3.5 et directplay pour tmnf
    #   ansible.windows.win_optional_feature:
    #     name: 
    #       - NetFx3
    #       - DirectPlay
    #     state: present
    #   tags:
    #     - tmnf
    #     - feature

    - name: copy trackmania exec
      win_copy:
        src: '\\192.168.1.3\partage\retrogame\tmnationsforever_setup.exe'
        dest: '%public%\desktop\retro\'
        remote_src: true
      tags:
        - tmnf

    - name: copy map tmnf
      win_copy:
        src: '\\serveur\partage\retrogame\map tmnf\'
        dest: 'C:\Users\Admin\Documents\TmForever\Tracks\Challenges\Downloaded\'
        remote_src: true
      tags:
        - after

    - name: copy revolt
      win_copy:
        src: '\\serveur\partage\retrogame\revolt'
        dest: '%public%\desktop\retro\revolt'
        remote_src: true
      tags:
        - revolt

    - name: install retrogame:zeus
      win_unzip:
        src: '\\serveur\partage\retrogame\Sierra.zip'
        dest: '%programfiles%\'
      tags:
        - retro
        - zeus
    
    - name: "create shortcut: zeus"
      win_shortcut:
        src: '%programfiles%\Sierra\Le Maître de l'' Olympe  Zeus\zeus.exe'
        dest: '%public%\desktop\retro\zeus.lnk'
        icon: '%programfiles%\Sierra\Le Maître de l'' Olympe  Zeus\zeus.exe,0'
        directory: '%programfiles%\Sierra\Le Maître de l'' Olympe  Zeus'
        state: present
      tags:
        - retro
        - zeus        
        - shortcut
        - tmp

    
    - name: "create shortcut: pinball"
      win_shortcut:
        src: 'https://alula.github.io/SpaceCadetPinball/'
        dest: '%public%\desktop\retro\pinball.lnk'       
        state: present
      tags:
        - retro
        - pinball        
        - shortcut

    - name: "create shortcut: pacman"
      win_shortcut:
        src: 'https://freepacman.org/'
        dest: '%public%\desktop\retro\pacman.lnk'       
        state: present
      tags:
        - retro
        - pacman        
        - shortcut
    ##copy openarena
    ##copy revolt
    ##make shortcut

    ## zeus/caesar

    # - name: add partage drive
    #   win_mapped_drive:
    #     letter: S
    #     path: \\192.168.1.3\partage
    #     state: absent

    #    #become: yes
    #   vars:
    #     become_method: runas
    #     become_user: "admin"
    #     become_pass: ''
    #   tags:
    #     - drive
